plugins {
    id 'java-library'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

group = 'com.fri4666.bweeep'
version = '0.1.0'

base {
    archivesName = 'bweeep-connection-lock-1201'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.0'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    add sourceSets.main, 'bweeep_connection_lock.refmap.json'
    config 'bweeep_connection_lock.mixins.json'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

tasks.named('jar', Jar).configure {
    finalizedBy 'reobfJar'
}