modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="bweeep_client"
version="1.0.0"
displayName="Bweeep Client"
authors="fri4666"
description='''
Keeps the Bweeep launcher client attached to its private server session.
'''

[[dependencies.bweeep_client]]
modId="neoforge"
type="required"
versionRange="[21.1.228,)"
ordering="NONE"
side="CLIENT"

[[dependencies.bweeep_client]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="CLIENT"
